/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MoreRouteImport } from './routes/more'
import { Route as SheltersRouteImport } from './routes/shelters'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SosNowRouteImport } from './routes/sos-now'
import { Route as SosStatusRouteImport } from './routes/sos-status'
import { Route as FamilyIdRouteImport } from './routes/family_.$id'
import { Route as SafeRouteIdRouteImport } from './routes/safe-route.$id'
import { Route as ShelterIdRouteImport } from './routes/shelter.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersRoute = SheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SosNowRoute = SosNowRouteImport.update({
  id: '/sos-now',
  path: '/sos-now',
  getParentRoute: () => rootRouteImport,
} as any)
const SosStatusRoute = SosStatusRouteImport.update({
  id: '/sos-status',
  path: '/sos-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIdRoute = FamilyIdRouteImport.update({
  id: '/family_/$id',
  path: '/family/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRouteIdRoute = SafeRouteIdRouteImport.update({
  id: '/safe-route/$id',
  path: '/safe-route/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterIdRoute = ShelterIdRouteImport.update({
  id: '/shelter/$id',
  path: '/shelter/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/family': typeof FamilyRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/more': typeof MoreRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
  '/sos-now': typeof SosNowRoute
  '/sos-status': typeof SosStatusRoute
  '/family/$id': typeof FamilyIdRoute
  '/safe-route/$id': typeof SafeRouteIdRoute
  '/shelter/$id': typeof ShelterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/family': typeof FamilyRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/more': typeof MoreRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
  '/sos-now': typeof SosNowRoute
  '/sos-status': typeof SosStatusRoute
  '/family/$id': typeof FamilyIdRoute
  '/safe-route/$id': typeof SafeRouteIdRoute
  '/shelter/$id': typeof ShelterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/family': typeof FamilyRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/more': typeof MoreRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
  '/sos-now': typeof SosNowRoute
  '/sos-status': typeof SosStatusRoute
  '/family_/$id': typeof FamilyIdRoute
  '/safe-route/$id': typeof SafeRouteIdRoute
  '/shelter/$id': typeof ShelterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/family'
    | '/guide'
    | '/help'
    | '/more'
    | '/shelters'
    | '/sos'
    | '/sos-now'
    | '/sos-status'
    | '/family/$id'
    | '/safe-route/$id'
    | '/shelter/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/family'
    | '/guide'
    | '/help'
    | '/more'
    | '/shelters'
    | '/sos'
    | '/sos-now'
    | '/sos-status'
    | '/family/$id'
    | '/safe-route/$id'
    | '/shelter/$id'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/family'
    | '/guide'
    | '/help'
    | '/more'
    | '/shelters'
    | '/sos'
    | '/sos-now'
    | '/sos-status'
    | '/family_/$id'
    | '/safe-route/$id'
    | '/shelter/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  FamilyRoute: typeof FamilyRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  MoreRoute: typeof MoreRoute
  SheltersRoute: typeof SheltersRoute
  SosRoute: typeof SosRoute
  SosNowRoute: typeof SosNowRoute
  SosStatusRoute: typeof SosStatusRoute
  FamilyIdRoute: typeof FamilyIdRoute
  SafeRouteIdRoute: typeof SafeRouteIdRoute
  ShelterIdRoute: typeof ShelterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters': {
      id: '/shelters'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos-now': {
      id: '/sos-now'
      path: '/sos-now'
      fullPath: '/sos-now'
      preLoaderRoute: typeof SosNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos-status': {
      id: '/sos-status'
      path: '/sos-status'
      fullPath: '/sos-status'
      preLoaderRoute: typeof SosStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family_/$id': {
      id: '/family_/$id'
      path: '/family/$id'
      fullPath: '/family/$id'
      preLoaderRoute: typeof FamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-route/$id': {
      id: '/safe-route/$id'
      path: '/safe-route/$id'
      fullPath: '/safe-route/$id'
      preLoaderRoute: typeof SafeRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter/$id': {
      id: '/shelter/$id'
      path: '/shelter/$id'
      fullPath: '/shelter/$id'
      preLoaderRoute: typeof ShelterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  FamilyRoute: FamilyRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  MoreRoute: MoreRoute,
  SheltersRoute: SheltersRoute,
  SosRoute: SosRoute,
  SosNowRoute: SosNowRoute,
  SosStatusRoute: SosStatusRoute,
  FamilyIdRoute: FamilyIdRoute,
  SafeRouteIdRoute: SafeRouteIdRoute,
  ShelterIdRoute: ShelterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
